MiniProjectWeb/Controllers/HomeController.cs
using MiniProject.data.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MiniProject.Data.Models;


namespace MiniProjectWeb.Controllers
{
    public class HomeController : Controller
    {
        private IRestaurantData restaurantData;

        public HomeController() => restaurantData = RestaurantDataProvider.Instance();

        public ActionResult Index()
        {
            List<MiniProject.data.Models.Restaurant> List = restaurantData.GetRestaurants();
            return View(List);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MiniProjectWeb/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using MiniProject.data.Models;
using MiniProject.Data.Models;
using MiniProject.data.Services;
using DishViewModel = MiniProject.Data.Models.DishViewModel;

namespace MiniProjectWeb.Controllers
{
    public class RestaurantController : Controller
    {
        
        private IRestaurantData restaurantData;
        
        [HttpGet]
        public ActionResult Index(int restaurantId, int? _dishId)
        {
            
            if (Session[restaurantId.ToString()] == null)
            {
                Session[restaurantId.ToString()] = new Dictionary<Dish, int>();
            }
            
            int dishId = _dishId ?? -1;
            restaurantData = RestaurantDataProvider.Instance();
            Restaurant restaurant = restaurantData.GetRestaurant(restaurantId);
            DishViewModel dishViewModel = new DishViewModel();
            dishViewModel.Restaurant = restaurant;
            if (dishId != -1)
            {
                Dish dish = restaurantData.GetDishById(restaurant, dishId);
                dishViewModel.Dish = dish;
                IDictionary<Dish, int> cartList = Session[restaurantId.ToString()] as Dictionary<Dish, int>;
                if (cartList.ContainsKey(dish)) {
                    cartList[dish]++;
                } else
                {
                    cartList.Add(dish, 1);
                }
                Session[restaurantId.ToString()] = cartList;
            }
            IDictionary<Dish, int> cart = Session[restaurantId.ToString()] as Dictionary<Dish, int>;
            dishViewModel.Cart = cart;
            
            return View(dishViewModel);
            
        }
        
        public ActionResult Cart(int restaurantId, int dishId = -1 , int actionId = -1 )
        {
            restaurantData = RestaurantDataProvider.Instance();
            Restaurant restaurant = restaurantData.GetRestaurant(restaurantId);
            DishViewModel dishViewModel = new DishViewModel();
            dishViewModel.Restaurant = restaurant;
            IDictionary<Dish, int> cart = Session[restaurantId.ToString()] as Dictionary<Dish, int>;
            if (actionId == 1)
            {
                Dish dish = restaurantData.GetDishById(restaurant, dishId);
                if (cart.ContainsKey(dish))
                {
                    cart[dish]++;
                }
                else
                {
                    cart.Add(dish, 1);
                }
                Session[restaurantId.ToString()] = cart;
            }
            else if (actionId == 2)
            {
                Dish dish = restaurantData.GetDishById(restaurant, dishId);
                if (cart.ContainsKey(dish))
                {
                    cart[dish]--;
                    if (cart[dish] == 0)
                    {
                        cart.Remove(dish);
                    }
                    Session[restaurantId.ToString()] = cart;
                }
            }
            dishViewModel.Cart = cart;
            if (dishViewModel.Cart.Count > 0)
            {
                return View(dishViewModel);
            } else
            {
                return RedirectToAction("Index", new {restaurantId = restaurantId});
            }
            
        }
    }
}

MiniProjectWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MiniProjectWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MiniProjectWeb/Views/Home/Index.cshtml
@model List<MiniProject.data.Models.Restaurant>
@{
    ViewBag.Title = "Home Page";
}

<h1 class="fs-1 mt-5">Top Rated Restaurants</h1>
<p>
    Ut cursus gravida tellus, eget maximus nisl malesuada nec. Phasellus nec leo quam. In faucibus diam mollis ultricies pharetra. Nam sit amet justo vel magna fringilla semper in ut libero.
</p>

<div class="row row-cols-2">
    @{ foreach (var restaurant in Model)
        {       
        <div class="col">               
            <div class="card mb-3 text-black" style="max-width: 540px;">
               
                <a href="@Url.Action("Index", "Restaurant", new {restaurantId = restaurant.RestaurantId})" style="text-decoration: none; color: currentColor">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <div class="ratio ratio-1x1">
                                <img src=@restaurant.Image class="img-fluid rounded-start" alt="...">
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">
                                    @restaurant.Name
                                    <span class="badge bg-danger">
                                        -@restaurant.Discount%
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-tag-fill" viewBox="0 0 16 16">
                                            <path d="M2 1a1 1 0 0 0-1 1v4.586a1 1 0 0 0 .293.707l7 7a1 1 0 0 0 1.414 0l4.586-4.586a1 1 0 0 0 0-1.414l-7-7A1 1 0 0 0 6.586 1H2zm4 3.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                                        </svg>
                                    </span>
                                </h5>
                                <p class="card-subtitle mb-2 text-muted">@restaurant.Address</p>
                                <p class="card-text">
                                    <small class="text-muted">
                                        @restaurant.Category - Average price : @restaurant.AveragePrice €
                                    </small>
                                </p>

                                <p class="card-text">
                                    @restaurant.Stars
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                                    </svg>
                                </p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>    
        </div>
        

        }
    }
</div>

MiniProjectWeb/Views/Restaurant/Cart.cshtml
@using MiniProject.Data.Models
@model MiniProject.Data.Models.DishViewModel

@{
    ViewBag.Title = "Cart of " + @Model.Restaurant.Name;
    float total = 0.0f;
}

<h1 class="mt-5">
    Cart of @Model.Restaurant.Name
</h1>
<div class="container">
    <div class="row justifiy-content-center">
        <div class="col-9">
            <ul class="list-group list-group-flush">
                @foreach (var dish in Model.Cart)
                {
                    float price = dish.Value * dish.Key.Price - (dish.Key.Price * (dish.Key.Discount / 100));
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">@dish.Value x @dish.Key.Name</div>
                            @dish.Key.Description
                            
                        </div>
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a href="/restaurant/Cart/?restaurantId=@Model.Restaurant.RestaurantId&dishId=@dish.Key.Id&actionId=2">
                                <button type="button" class="btn btn-outline-info">-</button>
                            </a>
                            <a href="/restaurant/Cart/?restaurantId=@Model.Restaurant.RestaurantId&dishId=@dish.Key.Id&actionId=1">
                                <button type="button" class="btn btn-outline-info">+</button>
                            </a>
                        </div>
                        <span class="badge bg-primary rounded-pill">@price €</span>
                    </li>
                    total += price;
                }
                @{
                    total += 5.0f;
                }
            </ul>
        </div>
        <div class="col-3 justify-content-center align-items-center">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">@Model.Restaurant.Name</h5>
                    <div class="ratio-1x1">
                        <img src=@Model.Restaurant.Image class="card-img-top img-fluid" alt="...">
                    </div>
                    <h6 class="card-subtitle mb-2 mt-2 text-muted">@Model.Restaurant.Address</h6>
                    <p class="card-text">Delivery fees : 5€</p>
                    <p class="card-text">Total to pay : @total €</p>
                    <a href="#" class="card-link">Pay</a>
                </div>
            </div>
        </div>
    </div>
    
</div>

MiniProjectWeb/Views/Restaurant/Index.cshtml
@model MiniProject.Data.Models.DishViewModel

@{
    ViewBag.Title = @Model.Restaurant.Name;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title> @Model.Restaurant.Name</title>
</head>
<body>
<div class="row mt-5">
    @if (@Model.Dish != null)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert mt-5">
            @Model.Dish.Name added to your cart!
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    }
    <div class="col">
        <h1 class="fs-1">@Model.Restaurant.Name</h1>
        <p> @Model.Restaurant.Address </p>
    </div>
</div>
@if (@Model.Cart.Count > 0)
{
    <a href="/restaurant/Cart/?restaurantId=@Model.Restaurant.RestaurantId">
        <button type="button" class="btn btn-primary">
            View Cart <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
                <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
            </svg>
        </button>
    </a>
}
<hr/>

@{
    foreach (var item in Model.Restaurant.Dishes.GroupBy(d => d.Category))
    {
        <h3 class="mt-5"> @item.Key </h3>
        <div class="row row-cols-1 row-cols-md-2 g-4">
            @foreach (var dish in item)
            {
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">@dish.Name</h5>
                            @if (dish.Discount != 0)
                            {
                                <h6 class="card-subtitle mb-2 text-muted"> - @dish.Discount%</h6>
                            }
                            <p class="card-text">@dish.Description</p>
                            @using (Html.BeginForm("Index", "Restaurant"))
                            {
                                <a href="/restaurant/Index/?restaurantId=@Model.Restaurant.RestaurantId&_dishId=@dish.Id">Ajouter au panier</a>
                            }
                        </div>
                        <div class="card-footer">
                            @dish.Price€
                            @if (dish.IsPopular)
                            {
                                <span class="text-warning"> -
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-stars" viewBox="0 0 16 16">
                                        <path d="M7.657 6.247c.11-.33.576-.33.686 0l.645 1.937a2.89 2.89 0 0 0 1.829 1.828l1.936.645c.33.11.33.576 0 .686l-1.937.645a2.89 2.89 0 0 0-1.828 1.829l-.645 1.936a.361.361 0 0 1-.686 0l-.645-1.937a2.89 2.89 0 0 0-1.828-1.828l-1.937-.645a.361.361 0 0 1 0-.686l1.937-.645a2.89 2.89 0 0 0 1.828-1.828l.645-1.937zM3.794 1.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387A1.734 1.734 0 0 0 4.593 5.69l-.387 1.162a.217.217 0 0 1-.412 0L3.407 5.69A1.734 1.734 0 0 0 2.31 4.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387A1.734 1.734 0 0 0 3.407 2.31l.387-1.162zM10.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732L9.1 2.137a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L10.863.1z"/>
                                    </svg> Popular </span>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    }
}

</body>
</html>

MiniProjectWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                @Html.ActionLink(System.Configuration.ConfigurationManager.AppSettings["AppName"], "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">@Html.ActionLink("Home", "Index","Home", "Home", new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </div>
<div class="container body-content">
    
    @RenderBody()
    <hr/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <footer>
        <p>&copy; @DateTime.Now.Year - @System.Configuration.ConfigurationManager.AppSettings["AppName"]</p>
    </footer>
</div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>